accessing-samples
pemPubKeyString2048
	"This is the public key of #pemPrivKeyString2048. Command to extract:
	 % openssl pkey -pubout -in keypair.pem"
	
	^ '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwKTK3eSSZ9Hmd7qVq352
Z1TMxUH/H0K79/ZzEqmM8o5AbXjPvVIHWmrtu23DwdQTSWu/6vyVUYGAnedJXXyM
lVE2whTnnR3I+CY0OsUBRrzx3dLqnCM1x9ftmXyTxhDmZ3Oki/sD7AG3AmTRnR/c
Gj8jpxpkdjESo7bKezPtAHSaB7O7DB249YE5ZKdgacTHVFSN6CMRw4pR0TlO0FFu
CPvXN1e8npmg+vez2P6xC+0TBzymiCNtFxzHy5EKYla0C6cVH4FVb7u0lWI4XJ/o
tddl9V7fxNil90cxQC664aEKHq+/q9rsVnOn4DZATaiyDusgPbVA/ijuXEAIY6CU
pQIDAQAB
-----END PUBLIC KEY-----'